Fix two "unused function" errors
When building on MacOS with Clang 11 the build fails with:

error: unused function 'get_chunk_rri'
error: unused function 'get_hyper_rri'
      [-Werror,-Wunused-function]

This PR fixes it.