Guard old openssl API functions
The openssl functions SSL_library_init(), SSL_load_error_strings(), and
ERR_free_strings() were deprecated in openssl 1.1.0, and shouldn't be
called on newer versions. In some runtime library versions, the symbols
may not even exist in the library anymore, leading to errors like:

  ERROR:  could not load library "/usr/pgsql-18/lib/timescaledb-2.25.1.so":
    /usr/pgsql-18/lib/timescaledb-2.25.1.so: undefined symbol: SSL_library_init