Fix build failure on PG12.0
Building against PG12.0 failed with
test_utils.c:99:5: error: expected ‘;’ before ‘errmsg’
because the errmsg argument was not in parens.