Swap message and detail in Ensure
The message will be "assertion 'true == false' failed", and the detail
will contain the description of the error. There are two reasons for
that:

1) Errdetail is not shown with the default psql settings. The
   description of the internal error might confuse the user, making them
think it's a system or a user error and try to troubleshoot it. The
primary message should make it clear that it is an internal program
error.
2) When debugging, the developer wants to see the failed condition and
   its location. Again, the default settings don't show the detail or
location of the error, so this information should be in the main message.

This is how the error report looks after the changes:
```
ERROR:  XX000: assertion 'false' at chunk.c:2174 failed
DETAIL:  the invariant 'false = true' is violated
```