Delete orphaned compression_settings before migrating catalog table
When upgrading from 2.18.2 to 2.19.0 with orphaned compression_settings
present the update would fail with:
ERROR:  null values cannot be formatted as an SQL identifier

(cherry picked from commit da9a30792f749c7d0f930c16fb028b0deed05a5b)