Safeguard against making invalid range types
In the invalidation logs metadata tables we have two columns
`lowest_modified_value` and `greatest_modified_value` and we don't have
any protection against inserting `greated_modified_value` less than
`lowest_modified_value`. In the new incremental policy refresh we build
int8 ranges based on those values so added some validations to don't end
up with errors trying to create an int8range from an invalid row.

On debug builds we have some assertion so this scenario will never
happen but on release builds it can happen when creating the batches to
be refreshed raising the following error:

ERROR:  range lower bound must be less than or equal to range upper bound