Fix CAgg order by pushdown
In the past the query against the materialization hypertable had
aggregation because we used to store the `chunk_id` in that table for
historic reasons (mostly because the multinode) and it was removed in
2.7.0 (PR #4294), but unfortunately we didn't reset the `ressortgroupref`
of the related target entries when building the materialization view
query and this gave the wrong assumption in the `cagg_sort_pushdown`
code that we have the right value to set the `tleSortGroupRef` for the
related `groupClause` of materialization hypertable range table entry.

So after a dump/restore when Postgres rebuild the views we got the
`ressortgroupref` for the materialization target entries leading to an
error:

ERROR: ORDER/GROUP BY expression not found in targetlist

Fixed it by setting the `ressortgroupref` with related `tleSortGroupRef`
instead and also added more regression tests to cover this issue.